"use client"
import { Button } from "@nextui-org/react";
import { useRouter } from "next/navigation";

export default function TermsOfService() {
    const router = useRouter();

    return (<div className="flex justify-center py-16 w-screen min-h-screen bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100 text-black dark:text-white/90 dark:[background-image:linear-gradient(45deg,#000000aa_16%,#312e8130,#581c8749,#83184330,black_84%)]">
        <div className="flex flex-col gap-2 max-w-2xl w-screen">
            <Button variant="light" className="max-w-fit" onClick={() => router.back()}>← back</Button>
            <div className="px-6 py-8 max-w-4xl mx-auto">
                <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
                <p className="text-sm text-gray-600 mb-6">Last Updated: 7th February 2025</p>

                <p className="mb-4">
                    Welcome to StudyPhii! These Terms and Conditions ("Terms") govern your use of our platform and services. By accessing or using StudyPhii, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use StudyPhii.
                </p>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">1. Definitions</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>
                            <strong>"StudyPhii"</strong> refers to our platform, including its website, application, and any related services we provide.
                        </li>
                        <li>
                            <strong>"User"</strong> refers to any individual or entity accessing StudyPhii.
                        </li>
                        <li>
                            <strong>"Content"</strong> refers to all text, images, AI-generated materials, and other information provided through StudyPhii.
                        </li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">2. Eligibility</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>You must be at least 13 years old to use StudyPhii. Users under 18 must have parental or guardian consent.</li>
                        <li>By using StudyPhii, you represent that you have the legal capacity to enter into this agreement.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">3. Use of StudyPhii</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>You agree to use StudyPhii for educational purposes only.</li>
                        <li>You must not:
                            <ul className="list-disc list-inside ml-6 space-y-2">
                                <li>Use the platform for any illegal activity.</li>
                                <li>Share or distribute harmful or inappropriate content.</li>
                                <li>Attempt to hack, disrupt, or interfere with StudyPhii’s functionality.</li>
                            </ul>
                        </li>
                        <li>We reserve the right to suspend or terminate your account if you violate these Terms.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">4. Account and Subscription</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>All pricing plans are non-refundable unless required by applicable law.</li>
                        <li>You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>StudyPhii retains all rights to its content, services, and branding.</li>
                        <li>Users may not copy, reproduce, or redistribute StudyPhii’s content without permission.</li>
                        <li>Content generated by StudyPhii’s AI tools is provided solely for personal, non-commercial use.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">6. User-Generated Content</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>
                            Any content you upload or input into StudyPhii remains your property. However, you grant StudyPhii a non-exclusive, royalty-free license to use, display, and distribute your content as needed to operate the platform.
                        </li>
                        <li>You are solely responsible for ensuring that your content does not violate any laws or infringe on third-party rights.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">7. Disclaimers and Limitation of Liability</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>StudyPhii is provided on an "as-is" basis. We do not guarantee that the platform will be error-free, secure, or available at all times.</li>
                        <li>StudyPhii does not guarantee any specific learning outcomes.</li>
                        <li>To the fullest extent permitted by law, StudyPhii shall not be liable for any direct, indirect, or incidental damages arising from your use of the platform.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">8. Privacy</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>StudyPhii’s handling of your data is governed by our <a href="#" className="text-blue-500 underline">Privacy Policy</a>.</li>
                        <li>By using StudyPhii, you consent to the collection and processing of your data as described in the Privacy Policy.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">9. Changes to Terms</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>We reserve the right to update these Terms at any time. Changes will take effect immediately upon posting on our platform.</li>
                        <li>Continued use of StudyPhii after changes constitutes your acceptance of the revised Terms.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">10. Termination</h2>
                    <ul className="list-disc list-inside space-y-2">
                        <li>We may suspend or terminate your access to StudyPhii if you violate these Terms.</li>
                        <li>Upon termination, your right to use StudyPhii will cease immediately.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-4">12. Contact Us</h2>
                    <p>
                        For questions or concerns about these Terms, please contact us at: <a href="mailto:hello@phii.space" className="text-blue-500 underline">hello@phii.space</a>.
                    </p>
                </section>
            </div>
        </div>
    </div>);
}